### ISSUE TITLE
Gather examples of OS licensing by agencies 

### ISSUE THREAD

**Issue by gbinal** [18F/open-source-program#13]

**Comment by rjmajma** [comment]
http://ti.arc.nasa.gov/opensource/nosa/

http://apps1.eere.energy.gov/buildings/energyplus/pdfs/open_source_agreement.pdf

Both refer to "world-wide, royalty free non-exclusive" license.

**Comment by polastre** [comment]
It would be good to have a "recommended" license by the OSP.  A "default" if you will.  There's currently no discussion on licensing at all, and it is the topic that comes up the most.
