### ISSUE TITLE
Add a 'Need Help?' sidebar item?

### ISSUE THREAD

**Issue by gbinal** [18F/open-source-program#32]
Does it make sense to add in the left sidebar - "Need Help?"

And then tell folks to hit up and ask for help at:
- Government Open Source group
- GitHub.com/Government 
- Mil-OSS group

**Comment by leahbannon** [comment]
Sounds great to me.

**Comment by virtix** [comment]
Perhaps an international group, too: https://plus.google.com/communities/110268213869494409273
