### ISSUE TITLE
Create a Case Studies section

### ISSUE THREAD

**Issue by gbinal** [18F/open-source-program#33]

**Comment by cew821** [comment]
Good ones to start with:

### Drupal
- www.energy.gov

### CKAN
- catalog.data.gov

### WordPress
- www.data.gov

**Comment by gbinal** [comment]
Eventually, I'd definitely love to collect any written case studies, [similar to this](http://18f.github.io/API-All-the-X/pages/case_study_lists).  I haven't found any yet, though.

**Comment by gbinal** [comment]
Need 1+ case study from NASA as a part of this

**Comment by gbinal** [comment]
Page is now live - http://18f.github.io/open-source-program/pages/case_study_list

It needs populating but I'm going to close this issue in the meantime
