### ISSUE TITLE
write more case studies 

### ISSUE THREAD

**Issue by gbinal** [18F/open-source-program#40]
Ideas include:
- NASA (which ones?).  E.G., code.nasa.gov story.  
- Walking the CFPB policy.  Problems, & how we got over the hurdles.  What were some concerns? Did it work? (Don't always need names, but types/groups of people.)  Privacy people.  
  -EPA GitHub Guidance  
  -Data.gov redesign  
  -White House website and/or api  
  energy.gov  
  catalog.data.gov

**Comment by gbinal** [comment]
From CFPB - https://github.com/cfpb/cfpb.github.io/issues/34

**Comment by virtix** [comment]
Not an official case study, but this has a lot of useful and related information: http://www.slideshare.net/ckleclerc/nasaoss-mattmann

**Comment by gbinal** [comment]
http://18f.github.io/open-source-program/pages/case_study/CFPB_open_source_documentation
