### ISSUE TITLE
migrate other OS/github stuff from other repos to here

### ISSUE THREAD

**Issue by gbinal** [18F/open-source-program#50]

**Comment by afeld** [comment]
What did you have in mind? I asked in chat about merging [the policy repo](https://github.com/18F/open-source-policy) repo in here – @konklone thought they should stay separate, and I'm on the fence.

**Comment by konklone** [comment]
Well, I feel _very_ strongly about keeping the policy at `18f/open-source-policy`. That policy is a very important permalink for our organization, and gets important eyeballs. I don't want to dilute or confuse the path to finding 18F's open source policy.

We could potentially merge these resources into that repo, somehow, but I still think they're worth keeping separate. I suspect the confusion of having two repos is felt greater by the 18F team than by the outside world.

**Comment by gbinal** [comment]
+1 to keeping the policy separate.  

I imagine I had in mind the material of government.github.com.
