### ISSUE TITLE
Sidebar overlapping with left footer 

### ISSUE THREAD

**Issue by gbinal** [18F/open-source-program#61]
@ultrasaurus - do you mind posting a screenshot of the entire window in which you're seeing this.

**Comment by gbinal** [comment]
The only ways I can replicate this so far have been by zooming in or by resizing the window until it's smaller.  @ultrasaurus - is the browser window reasonably large?

**Comment by gbinal** [comment]
Regardless, it's easy to address by just removing the footer info.  I'm not sure it's really all that useful.

**Comment by gbinal** [comment]
Commented it out with https://github.com/18F/open-source-program/commit/332558e2fc29ef99c520d49376268dfe06b6502e.   Should be fixed.

**Comment by ultrasaurus** [comment]
comfirmed fixed.  Footer is no longer present
