### ISSUE TITLE
Promote use of `./go` script (or equivalent) in maintainer guidelines

### ISSUE THREAD

**Issue by mbland** [18F/open-source-program#62]
In the [maintainer guidelines](https://18f.github.io/open-source-program/pages/maintainer_guidelines/), I think it'd be helpful to promote the `./go` script convention to make building, launching, and deploying a project as easy as possible (a la [the 18F Hub](https://github.com/18F/hub#generating-the-sitehosting-locally)).

**Comment by mbland** [comment]
cc: @afeld @msecret

**Comment by afeld** [comment]
I think the important thing to convey is not whether it's called `go` or `setup` or `bootstrap` or `make install` – more that it's about making setup as easy as possible, and scripting that is a big win.

Related documentation:
- https://robots.thoughtbot.com/bin-setup
- http://wynnnetherland.com/linked/2013012801/bootstrapping-consistency/

**Comment by monfresh** [comment]
:100: to @afeld.

**Comment by ultrasaurus** [comment]
FYI: might not be an issue for most projects, but bash / make create additional dependencies on Windows.  You might want to caveat the promotion of the ./go script convention...

**Comment by mbland** [comment]
Very fair point. Or it could be that there needs to be a `./go-windows` script, too.

**Comment by afeld** [comment]
As noted in https://github.com/18F/midas/issues/741#issuecomment-96776923, one alternative solution may be to have the user install whatever primary language is being used for the project (Node, Ruby, etc.) then have a script in that language that does the rest.
