### ISSUE TITLE
move the maintainer guidelines to a Guide

### ISSUE THREAD

**Issue by afeld** [18F/open-source-program#63]
I think the [maintainer guidelines](https://pages.18f.gov/open-source-program/pages/maintainer_guidelines/) have a lot of potential, but they are fairly buried in this site. It is large enough to live on its own and would work well in the [Guide](https://pages.18f.gov/guides-template/) format, so I propose moving it out.

/cc https://github.com/18F/blog-drafts/issues/246#issuecomment-123423013 @melodykramer

**Comment by afeld** [comment]
Presumably this repository is a placeholder? https://github.com/18F/open-source-guide

**Comment by melodykramer** [comment]
That's right. Should be done today!

**Comment by melodykramer** [comment]
https://pages.18f.gov/open-source-guide/
