### ISSUE TITLE
more github orgs 

### ISSUE THREAD

**Issue by gbinal** [18F/open-source-program#75]
https://github.com/llnl
https://github.com/scalability-llnl

**Comment by gbinal** [comment]
sbstusa

**Comment by gbinal** [comment]
https://github.com/DistributedOpenUnifiedGovernmentNetwork

**Comment by gbinal** [comment]
https://github.com/CMSgov

**Comment by gbinal** [comment]
https://github.com/USCIS

**Comment by gbinal** [comment]
https://github.com/USDA-FSA

**Comment by gbinal** [comment]
https://github.com/openopps

**Comment by afeld** [comment]
Checked to make sure that all of these are reflected at government.github.com, and added the ones that weren't there:
- https://github.com/github/government.github.com/issues/467
- https://github.com/github/government.github.com/pull/468

**Comment by gbinal** [comment]
https://github.com/USDA-FSA

**Comment by gbinal** [comment]
https://github.com/llnl

**Comment by gbinal** [comment]
https://github.com/usnistgov

**Comment by gbinal** [comment]
http://uspto.github.io/designpatterns/

**Comment by gbinal** [comment]
http://usnationalarchives.github.io/capstone-grs/

**Comment by gbinal** [comment]
github.com/usedgov

**Comment by gbinal** [comment]
https://github.com/uspki

**Comment by gbinal** [comment]
https://github.com/usdot-jpo-ode

**Comment by gbinal** [comment]
https://github.com/iadgov

**Comment by gbinal** [comment]
https://github.com/dhs-ncats

**Comment by gbinal** [comment]
https://github.com/armycyberschool

**Comment by afeld** [comment]
@gbinal Rather than maintaining our own list, cool if we just refer to https://government.github.com/community/?

**Comment by gbinal** [comment]
Thanks, @afeld.  This issue is for loose notes that I use for myself and that I'd reference to anyone else only after government.github.com and the [Digital Registry](https://www.digitalgov.gov/services/u-s-digital-registry/).  

I'd missed that the former had added instructions on how to add to the page, but will try to make a note to prioritize that in the future.

**Comment by gbinal** [comment]
https://github.com/mil-oss
